[Catpuccin]
# Base UI Elements
background      = "#1e1e2e"
area1           = "#181825"
area2           = "#11111B"
highlighted     = "#45475A"

# Text related
text            = "#cdd6f4"
disabledText    = "#363659"
highlightedText = "#30304b"

# Element related
icon            = "#6c7086"
indicator       = "#ffcc66"
panelIndicator  = "#cba6f7"
handleIndicator = "#89dceb"
active          = "#1e1e2e"
inactive        = "#6c7086"
splitter        = "#313244"
